#This playbbok will install HTTP server,wget and vim package using loops.

---
- hosts: web
  become: yes
  tasks:
    - name: Install list of packages
      apt: 
        name: '{{item}}' 
        state: present
      loop:
       - wget
       - vim
       - zip
       - unzip  
...
*************************  
#This playbbok will install HTTP server,wget and vim package using loops.

---
- hosts: test-server
  become: yes
  tasks:
    - name: Install list of packages
      yum:
        name: '{{item}}'
        state: present
      loop:
       - wget
       - vim
       - zip
       - unzip
...

